### ISSUE TITLE
Print PHP code issue

### ISSUE THREAD

**Issue by evolvewebtech** [vakata/php-lpd#1]
Hi 

When i am running this code it is giving this error:

Warning: stream_socket_client(): unable to connect to tcp://81.174.152.8:9100 (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. )

Sometime it gives blank page. And gives timeout issue.

Please suggest me what i can do?

Thanks
Amit

**Comment by vakata** [comment]
What are you doing - using the client or the server? Are you using the correct port - the server opens up port `515` by default (and the client connects on that port by default too). 

Could you share the way you are creating the server? 

Also keep in mind this might be a networking issue - maybe the port you are using is not opened to the world.

Please share more information about your setup and I will reopen the issue.

Best regards,
Ivan

**Comment by evolvewebtech** [comment]
Hi 

Thanks for your response:

I am using client.php and using this code:

set_time_limit(0);
error_reporting(E_ALL);
ob_implicit_flush();

require_once(dirname(**FILE**) . DIRECTORY_SEPARATOR . 'class.lpr.php');
$lpr = new PrintSendLPR();
$lpr->setHost("81.174.152.8");
$lpr->setPort("9100");
$lpr->setData("Some text to test.");
echo $lpr->printJob("test");

If i am printing using CMD-> "telnet 81.174.152.8 9100" than it is printing. 

But when i am printing using our php code. It is giving following error:
1. Warning: stream_socket_client(): unable to connect to tcp://81.174.152.8:9100 (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. )
2. Connection timeout issue
3. Maximum execution time issue.

Please let me know, feel free to ask me any questions.

Thanks
Amit

**Comment by vakata** [comment]
I am afraid I can't help you - I did not write the client class (as seen in the comments), I just use it to provide a demo. If you have a problem with the server - let me know, otherwise, try finding the author of the client class:

```
/*
 * Class PrintSend - Abstract printing class.
 * Models the actual sending of data to the printer.
 * 
 * Author: Mick Sear
 * eCreate, Aug 2005
 */
```

Best regards,
Ivan

**Comment by evolvewebtech** [comment]
Hi,

I also tried with server.php.

So i am getting following error:
I am using IP: 81.174.152.8
Port 9100

Warning: socket_bind(): unable to bind address [10049]: The requested address is not valid in its context. in E:\xampp\htdocs\PhpPrint\php-lpd-master\class.lpd.php on line 15

Notice: Undefined variable: sock in E:\xampp\htdocs\PhpPrint\php-lpd-master\class.lpd.php on line 16

Warning: socket_last_error() expects parameter 1 to be resource, null given in E:\xampp\htdocs\PhpPrint\php-lpd-master\class.lpd.php on line 16

Fatal error: Uncaught exception 'Exception' with message 'socket_bind() failed: reason: The operation completed successfully. ' in E:\xampp\htdocs\PhpPrint\php-lpd-master\class.lpd.php:16 Stack trace: #0 E:\xampp\htdocs\PhpPrint\php-lpd-master\example\server.php(10): LPD->__construct(Object(Closure)) #1 {main} thrown in E:\xampp\htdocs\PhpPrint\php-lpd-master\class.lpd.php on line 16

Please let me know your thoughts.

**Comment by vakata** [comment]
How did you "try" `server.php`? Do you need to print something on an existing printer or create a virtual PHP printer? Those are two completely different tasks - `client.php` does the first, `server.php` - the second.
From what I see, `81.174.152.8` is not your own IP, so my guess is you are trying to print something on a real printer somewhere. In that case `server.php` is of absolutely no use to you.

If you want to print something on this IP - `class.lpr.php` is what you need, but once again **I did not write this file, and I do not support it, it is just there to provide an example**. If you are having problems starting a virtual PHP printer on your own LOCAL IP - let me know - that is the part I wrote.

Best regards,
Ivan
